# MariaDB configuration
mariadb:
  deployment:
    image: mariadb:11.6-ubi
    databaseName: slurm_accounting
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  secret:
    username: "slurm"
    password: "${SLURM_DB_PASSWORD}"

# Slurm components
slurmdbd:
  deployment:
    image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
slurmctld:
  deployment:
    image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
slurmd:
  deployment:
    image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
    replicaCount: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "1000m"

# The Slurm node watcher (adds and removes slurmd nodes via scrontrol)
nodeWatcher:
  deployment:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

volumes:
  mariadb:
    # A persistent volume for /var/lib/mysql is required.
    - name: mariadb-data
      mountPath: /var/lib/mysql
      # Optional, defaults to Retain
      reclaimPolicy: Delete
      size: 50Gi
      storageClassName: local-ssd
      accessModes:
        - ReadWriteOnce
      spec:
        hostPath:
          path: /apps/slurm-cluster/mariadb/data
          type: DirectoryOrCreate
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - lavender
    # List more volumes and they will be mounted into the component's container.
  munge:
    # A persistent volume for /etc/munge is required.
    - name: munge-etc
      mountPath: /etc/munge
      # Optional, defaults to Retain
      reclaimPolicy: Delete
      size: 1Gi
      storageClassName: local-ssd
      accessModes:
        - ReadWriteMany
      spec:
        hostPath:
          path: /apps/slurm-cluster/munge/etc
          type: DirectoryOrCreate
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - lavender
    # List more volumes and they will be mounted into the component's container.
  nodeWatcher: []
  slurmctld:
    # A persistent volume for /var/spool/slurmctld is required.
    - name: slurmctld-spool
      mountPath: /var/spool/slurmctld
      # Optional, defaults to Retain
      reclaimPolicy: Delete
      size: 10Gi
      storageClassName: local-ssd
      accessModes:
        - ReadWriteOnce
      spec:
        hostPath:
          path: /apps/slurm-cluster/slurmctld/spool
          type: DirectoryOrCreate
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - lavender
    # List more volumes and they will be mounted into the component's container.
  slurmdbd: []
  slurmd:
    # slurmd does not require any volumes. The entries below are just examples.
    # NFS example
    #- name: home
    #  mountPath: /home
    #  # Optional, defaults to Retain
    #  reclaimPolicy: Delete
    #  size: 10Gi
    #  storageClassName: local-ssd
    #  accessModes: 
    #    - ReadWriteMany
    #  spec:
    #    nfs:
    #      server: aster.your.domain
    #      path: /apps/slurm-cluster/slurmd/home

    # HostPath example
    #- name: data
    #  mountPath: /data
    #  # Optional, defaults to Retain
    #  reclaimPolicy: Delete
    #  size: 10Gi
    #  storageClassName: local-ssd
    #  accessModes:
    #    - ReadWriteMany
    #  spec:
    #    hostPath:
    #      path: /apps/slurm-cluster/slurmd/data
    #      type: DirectoryOrCreate
    #    nodeAffinity:
    #      required:
    #        nodeSelectorTerms:
    #        - matchExpressions:
    #          - key: kubernetes.io/hostname
    #            operator: In
    #            values:
    #            - lavender

    # Using an existing PV
    #- name: shared
    #  mountPath: /shared
    #  size: 100Gi
    #  volumeName: shared-pv
    #  accessModes:
    #    - ReadWriteMany

    # Creating a new PV
    #- name: scratch
    #  mountPath: /scratch
    #  size: 50Gi
    #  type: dynamic
    #  storageClassName: fast-storage
    #  accessModes:
    #    - ReadWriteOnce

# Health checks
probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5

# Security settings
podSecurityContext:
  runAsUser: 980
  runAsGroup: 980
  fsGroup: 980

# Ingress to expose slurmctld
ingressNginx:
  enabled: false
  controller:
    config:
      enable-tcp-services: true
    tcp:
      configMapNamespace: ingress-nginx
      configMapName: tcp-services

replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}

metrics-server:
  args:
    - --kubelet-insecure-tls

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # Annotations to add to the service account
  annotations: {}
  # Whether to automount the service account token
  automount: true
