apiVersion: v1
kind: Namespace
metadata:
  name: slurm-cluster
---
# MariaDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slurm-mariadb-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  local:
    path: /apps/slurm-cluster/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lavender
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-mariadb-pvc
  namespace: slurm-cluster
spec:
  storageClassName: local-ssd
  volumeName: slurm-mariadb-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: slurm-cluster
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: slurm-cluster
data:
  custom.cnf: |
    [mysqld]
    innodb_buffer_pool_size=4G
    innodb_lock_wait_timeout=900
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: slurm-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root
              key: password
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-root
              key: username
        - name: MARIADB_DATABASE
          value: "slurm-cluster"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: mariadb-config
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: slurm-mariadb-pvc
      - name: mariadb-config
        configMap:
          name: mariadb-config
---
# Munge
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slurm-etc-munge-dir-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  local:
    path: /apps/slurm-cluster/munge
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lavender
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-munge-dir-pvc
  namespace: slurm-cluster
spec:
  storageClassName: local-ssd
  volumeName: slurm-etc-munge-dir-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# slurmdbd
apiVersion: v1
kind: Service
metadata:
  name: slurmdbd
  namespace: slurm-cluster
spec:
  selector:
    app: slurmdbd
  ports:
    - protocol: TCP
      port: 6819
      targetPort: 6819
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slurmdbd-config
  namespace: slurm-cluster
data:
  slurmdbd.conf: |
    ArchiveEvents=yes
    ArchiveJobs=yes
    ArchiveResvs=yes
    ArchiveSteps=no
    ArchiveSuspend=no
    ArchiveTXN=no
    ArchiveUsage=no
    #ArchiveScript=/usr/sbin/slurm.dbd.archive
    AuthInfo=/var/run/munge/munge.socket.2
    AuthType=auth/munge
    DbdHost=slurmdbd
    DebugLevel=info
    PurgeEventAfter=1month
    PurgeJobAfter=3month
    PurgeResvAfter=1month
    PurgeStepAfter=1month
    PurgeSuspendAfter=1month
    PurgeTXNAfter=3month
    PurgeUsageAfter=6month
    LogFile=/var/log/slurmdbd.log
    PidFile=/var/run/slurmdbd.pid
    SlurmUser=slurm
    StorageHost=mariadb.slurm-cluster.svc.cluster.local
    StoragePass=STORAGE_PASS
    StorageType=accounting_storage/mysql
    StorageUser=STORAGE_USER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmdbd
  namespace: slurm-cluster
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: slurmdbd
  template:
    metadata:
      labels:
        app: slurmdbd
    spec:
      hostname: slurmdbd
      initContainers:
      - name: copy-slurmdbd-conf
        image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
          - -c
          - |
            mkdir -p /etc/slurm && \
            cp /configmap/slurmdbd.conf /etc/slurm/slurmdbd.conf && \
            sed -i "s/STORAGE_PASS/${STORAGE_PASS}/g" /etc/slurm/slurmdbd.conf && \
            sed -i "s/STORAGE_USER/${STORAGE_USER}/g" /etc/slurm/slurmdbd.conf      
        volumeMounts:
        - name: configmap-volume
          mountPath: /configmap
        - name: etc-slurm-dir
          mountPath: /etc/slurm
        env:
        - name: STORAGE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-root
              key: username
        - name: STORAGE_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-root
              key: password
      containers:
      - name: slurmdbd
        image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
          - /usr/local/bin/entrypoint.sh 
          - launch_slurmdbd
        env:
        - name: STORAGE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-root
              key: username
        - name: STORAGE_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-root
              key: password
        volumeMounts:
        - name: etc-slurm-dir
          mountPath: /etc/slurm
        - name: etc-munge-dir
          mountPath: /etc/munge
        ports:
        - containerPort: 6819
      volumes:
      - name: configmap-volume
        configMap:
          name: slurmdbd-config
      - name: etc-slurm-dir
        emptyDir: {}
      - name: etc-munge-dir
        persistentVolumeClaim:
          claimName: etc-munge-dir-pvc
---
# slurm.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: slurm-config
  namespace: slurm-cluster
data:
  slurm.conf: |
    ClusterName=slurm-cluster
    SlurmctldHost=slurmctld
    MpiDefault=none
    #ProctrackType=proctrack/cgroup
    ProctrackType=proctrack/linuxproc
    ReturnToService=2
    SlurmctldPidFile=/var/run/slurmctld.pid
    SlurmctldPort=6817
    SlurmdPidFile=/var/run/slurmd.pid
    SlurmdPort=6818
    SlurmdSpoolDir=/var/spool/slurmd
    SlurmUser=slurm
    SlurmdUser=slurm
    StateSaveLocation=/var/spool/slurmctld
    SwitchType=switch/none
    SlurmctldParameters=cloud_dns,enable_configless,write_config_on_change

    # TIMERS
    InactiveLimit=0
    KillWait=30
    MinJobAge=300
    SlurmctldTimeout=120
    SlurmdTimeout=300
    Waittime=0
    
    # SCHEDULING
    SchedulerType=sched/backfill
    SelectType=select/cons_tres
    SelectTypeParameters=CR_Core_Memory
    
    # LOGGING AND ACCOUNTING
    AccountingStorageHost=slurmdbd
    AccountingStorageType=accounting_storage/slurmdbd
    JobCompType=jobcomp/none
    JobAcctGatherFrequency=30
    #JobAcctGatherType=jobacct_gather/cgroup
    JobAcctGatherType=jobacct_gather/linux
    SlurmctldDebug=info
    SlurmctldLogFile=/var/log/slurmctld.log
    SlurmdDebug=info
    SlurmdLogFile=/var/log/slurmd.log
    
    # COMPUTE NODES
    MaxNodeCount=1000
    #NodeName=slurmd CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=8 ThreadsPerCore=2 RealMemory=128717
    PartitionName=main Nodes=ALL Default=YES MaxTime=INFINITE State=UP
---
# Slurmctld
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slurmctld-spool-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  local:
    path: /apps/slurm-cluster/slurmctld-spool
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lavender
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurmctld-spool-pvc
  namespace: slurm-cluster
spec:
  storageClassName: local-ssd
  volumeName: slurmctld-spool-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: slurmctld
  namespace: slurm-cluster
spec:
  selector:
    app: slurmctld
  ports:
    - protocol: TCP
      port: 6817
      targetPort: 6817
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmctld
  namespace: slurm-cluster
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: slurmctld
  template:
    metadata:
      labels:
        app: slurmctld
    spec:
      hostname: slurmctld
      initContainers:
      - name: copy-slurm-conf
        image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
          - -c
          - |
            cp /configmap/slurm.conf /etc/slurm/slurm.conf
        volumeMounts:
        - name: configmap-volume
          mountPath: /configmap
        - name: etc-slurm-dir
          mountPath: /etc/slurm
      containers:
      - name: slurmctld
        image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
          - /usr/local/bin/entrypoint.sh
          - launch_slurmctld
        volumeMounts:
        - name: etc-slurm-dir
          mountPath: /etc/slurm
        - name: etc-munge-dir
          mountPath: /etc/munge
        - name: slurmctld-spool-pv
          mountPath: /var/spool/slurmctld
      volumes:
      - name: configmap-volume
        configMap:
          name: slurm-config
      - name: etc-slurm-dir
        emptyDir: {}
      - name: etc-munge-dir
        persistentVolumeClaim:
          claimName: etc-munge-dir-pvc
      - name: slurmctld-spool-pv
        persistentVolumeClaim:
          claimName: slurmctld-spool-pvc
---
# Slurmd
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmd
  namespace: slurm-cluster
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
      matchLabels:
        app: slurmd
  template:
    metadata:
      labels:
        app: slurmd
    spec:
      initContainers:
      - name: copy-slurm-conf
        image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
          - -c
          - |
            cp /configmap/slurm.conf /etc/slurm/slurm.conf
        volumeMounts:
        - name: configmap-volume
          mountPath: /configmap
        - name: etc-slurm-dir
          mountPath: /etc/slurm
      containers:
      - name: slurmd
        image: docker-registry.jealwh.local:5000/slurm:24-11-0-1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        command: ["/bin/bash"]
        args:
          - /usr/local/bin/entrypoint.sh
          - launch_slurmd
        volumeMounts:
        - name: etc-slurm-dir
          mountPath: /etc/slurm
        - name: etc-munge-dir
          mountPath: /etc/munge
      volumes:
      - name: configmap-volume
        configMap:
          name: slurm-config
      - name: etc-slurm-dir
        emptyDir: {}
      - name: etc-munge-dir
        persistentVolumeClaim:
          claimName: etc-munge-dir-pvc
---
