{{- range $component, $config := (dict "munge" .Values.volumes.munge "slurmd" .Values.volumes.slurmd) }}
{{- if $config }}
{{- range $config }}
{{- $fullname := (include "slurm-cluster.fullname" $) }}
{{- $namespace := $.Release.Namespace }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullname }}-{{ .name }}-pvc
  labels:
    {{- include "slurm-cluster.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  accessModes: {{ .accessModes | toJson }}
  resources:
    requests:
      storage: {{ .size }}
  {{- if and .volumeName (not .storageClass) }}
  volumeName: {{ .volumeName }}
  {{- else if and .storageClass (not .volumeName) }}
  volumeName: {{ $fullname }}-{{ $namespace }}-{{ .name }}-pv
  storageClassName: {{ .storageClass }}
  {{- else }}
  volumeName: {{ $fullname }}-{{ $namespace }}-{{ .name }}-pv
  storageClassName: {{ .storageClassName }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
