apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "slurm-cluster.fullname" . }}-mariadb-pv
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  capacity:
    storage: {{ .Values.mariadb.storage.data.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mariadb.storage.data.storageClass }}
  local:
    path: {{ .Values.mariadb.storage.data.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          {{- range .Values.mariadb.storage.data.nodeAffinityHostnames }}
          - {{ . }}
          {{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "slurm-cluster.fullname" . }}-munge-pv
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: munge
spec:
  capacity:
    storage: {{ .Values.munge.storage.data.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.munge.storage.data.storageClass }}
  local:
    path: {{ .Values.munge.storage.data.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          {{- range .Values.munge.storage.data.nodeAffinityHostnames }}
          - {{ . }}
          {{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "slurm-cluster.fullname" . }}-slurmctld-spool-pv
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: slurmctld
spec:
  capacity:
    storage: {{ .Values.slurmctld.storage.data.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.slurmctld.storage.data.storageClass }}
  local:
    path: {{ .Values.slurmctld.storage.data.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          {{- range .Values.slurmctld.storage.data.nodeAffinityHostnames }}
          - {{ . }}
          {{- end }}
