apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slurm-cluster.fullname" . }}-munge-pvc
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: munge
spec:
  storageClassName: {{ .Values.munge.storage.data.storageClass }}
  volumeName: {{ include "slurm-cluster.fullname" . }}-munge-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.munge.storage.data.size }}
