apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm-cluster.fullname" . }}-mariadb-root
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
data:
  username: {{ .Values.mariadb.secret.username | toString | b64enc | quote }}
  password: {{ .Values.mariadb.secret.password | toString | b64enc | quote }}
