apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm-cluster.fullname" . }}-mariadb-root
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
data:
  username: {{ if (and .Values.secrets .Values.secrets.mariadb .Values.secrets.mariadb.username) }}{{ .Values.secrets.mariadb.username | toString | b64enc | quote }}{{ else }}{{ "root" | b64enc | quote }}{{ end }}
  {{- $password := include "mariadb.getPassword" . }}
  password: {{ $password | b64enc | quote }}
