apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  selector:
    {{- include "slurm-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: slurmdbd
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: slurmdbd
spec:
  selector:
    {{- include "slurm-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: slurmdbd
  ports:
    - protocol: TCP
      port: 6819
      targetPort: 6819
---
apiVersion: v1
kind: Service
metadata:
  name: slurmctld
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: slurmctld
spec:
  selector:
    {{- include "slurm-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: slurmctld
  ports:
    - protocol: TCP
      port: 6817
      targetPort: 6817
